openapi: 3.0.0
info:
  title: 마이크로서비스 API
  version: 1.0.0
  description: 여러 마이크로서비스로 구성된 API 예시

servers:
  - url: http://api.example.com
    description: API Gateway

paths:
  /api/orders:
    get:
      summary: 주문 목록 조회
      operationId: getOrders
      security:
        - apiKey: []
      responses:
        '200':
          description: 성공
    post:
      summary: 주문 생성
      operationId: createOrder
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
      responses:
        '201':
          description: 생성됨
      # Rate Limit 권장

  /api/payments:
    post:
      summary: 결제 처리
      operationId: processPayment
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: integer
                amount:
                  type: number
                creditCard:
                  type: string
      responses:
        '200':
          description: 성공
      # 민감한 작업 - Rate Limit 필수

  /api/inventory:
    get:
      summary: 재고 조회
      operationId: getInventory
      security:
        - apiKey: []
      parameters:
        - name: productId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: 성공

  /api/notifications:
    post:
      summary: 알림 전송
      operationId: sendNotification
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                message:
                  type: string
      responses:
        '200':
          description: 성공
      # Rate Limit 권장

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

