openapi: 3.0.0
info:
  title: 취약한 사용자 관리 API
  version: 1.0.0
  description: OWASP Top 10 취약점이 다수 포함된 예시 API

servers:
  - url: http://api.example.com
    description: 프로덕션 서버

paths:
  /api/users/{userId}:
    get:
      summary: 사용자 정보 조회 (BOLA 취약)
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  password:
                    type: string
                  creditCard:
                    type: string
                  ssn:
                    type: string
      # 인증/인가 없음 - BOLA 취약점

  /api/admin/users:
    get:
      summary: 모든 사용자 조회 (권한 체크 없음)
      operationId: getAllUsers
      responses:
        '200':
          description: 성공
      # 권한 체크 없음 - Broken Function Level Authorization

  /api/auth/login:
    post:
      summary: 로그인 (취약한 인증)
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      # JWT 검증 로직 없음 - Broken Authentication

  /api/payment/process:
    post:
      summary: 결제 처리 (Rate Limit 없음)
      operationId: processPayment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                creditCard:
                  type: string
      responses:
        '200':
          description: 성공
      # Rate Limit 없음 - Unrestricted Access to Sensitive Business Flows

  /api/proxy:
    get:
      summary: 프록시 요청 (SSRF 취약)
      operationId: proxyRequest
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공
      # URL 검증 없음 - SSRF 취약점

